name: immich

networks:
  immich_default:
    external: true

volumes:
  immich_model-cache:
    external: true
  immich_postgres_data:
  immich_redis_data:

services:
  immich_server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION}
    restart: always
    environment:
      - DB_HOSTNAME=immich_postgres
      - REDIS_HOSTNAME=immich_redis
      - DB_PASSWORD=${IMMICH_DB_PASS}
      - DB_USERNAME=${IMMICH_DB_USER}
      - DB_DATABASE_NAME=${IMMICH_DB_NAME}
      - UPLOAD_LOCATION=${IMMICH_UPLOAD_LOCATION}
    devices:
      - /dev/dri:/dev/dri
    networks:
      - immich_default
    ports:
      - "2283:2283"
    depends_on:
      - immich_redis
      - immich_postgres
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${IMMICH_UPLOAD_LOCATION}:/usr/src/app/upload
      - ./data:/data
  
  immich_microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION}
    # Note: Microservices uses the SAME image as Server, just a different command.
    command: [ "start.sh", "microservices" ] 
    restart: always
    environment:
      - DB_HOSTNAME=immich_postgres
      - REDIS_HOSTNAME=immich_redis
      - DB_PASSWORD=${IMMICH_DB_PASS}
      - DB_USERNAME=${IMMICH_DB_USER}
      - DB_DATABASE_NAME=${IMMICH_DB_NAME}
      - UPLOAD_LOCATION=${IMMICH_UPLOAD_LOCATION}
    networks:
      - immich_default
    depends_on:
      - immich_redis
      - immich_postgres
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${IMMICH_UPLOAD_LOCATION}:/usr/src/app/upload
      - ./data:/data

  immich-machine-learning:
    container_name: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION}-openvino
    restart: always
    environment:
      - DB_HOSTNAME=immich_postgres
      - REDIS_HOSTNAME=immich_redis
      - DB_PASSWORD=${IMMICH_DB_PASS}
      - DB_USERNAME=${IMMICH_DB_USER}
      - DB_DATABASE_NAME=${IMMICH_DB_NAME}
    devices:
      - /dev/dri:/dev/dri
    networks:
      - immich_default
    volumes:
      - immich_model-cache:/cache

  immich_postgres:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0
    restart: always
    environment:
      - POSTGRES_PASSWORD=${IMMICH_DB_PASS}
      - POSTGRES_USER=${IMMICH_DB_USER}
      - POSTGRES_DB=${IMMICH_DB_NAME}
      - PGDATA=/var/lib/postgresql/data
    networks:
      - immich_default
    volumes:
      - immich_postgres_data:/var/lib/postgresql/data

  immich_redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm
    restart: always
    networks:
      - immich_default
    volumes:
      - immich_redis_data:/data
